server:
  port: 8080

#spring config
spring:
  application:
    name: boot_develop
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:C:/testDb/h2/boot_develop
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    //database-platform: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: boot_develop
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#       path: h2
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/webapp/
h2:
  tcp:
    port: 8180
    enabled: false
  web:
    port: 8280
    enabled: true
    
keycloak:
  auth-server-url: http://10.188.21.107:8080/auth
  realm: boot_develop
  resource: boot_develop
#  bearer-only: true
  public-client: true
#  use-resource-role-mappings: true
#  confidential-port: 0
  principal-attribute: preferred_username
#  security-constraints:
#  - 
#    authRoles:
#     - common_ro    
#    securityCollections:   
#     -
#      patterns:
#       - /**
          
  
keycloak-admin:
  master-realm: master
  admin-username: admin
  admin-pass: 123456
  admin-client-id: admin-cli
  admin-client-secret: c5660b49-426c-45e6-8a78-c9eb3f20b1e6
  identity-provider: